use std::str::FromStr;

grammar;

pub RecordValue: (String, u32, Option<char>) = {
    "<" <k:Key> ":" <l:Len> <t:Type?> ">" => (k, l, t)
};

// Definition for a record value's key
Key: String = <s:r"[A-Za-z_]+"> => String::from(s).to_uppercase();

// Definition for a record value's length
Len: u32 = <s:r"[0-9]+"> => u32::from_str(s).unwrap();

// Definition for a record value's type
Type: char = <s:r":[A-Za-z]"> => String::from(s).to_uppercase().chars().nth(1).unwrap();